<?php

class Notification extends CI_Model {

    public function setToken($token, $id, $user) {
        
        $this->db->where('token', $token);
        $query = $this->db->get('notif');
        $data = $query->row();
        $tokenData = array (
            'token' => $token,
            'user_id' => $id,
            'user' => $user
        );

        if (empty($data)) {
                $this->db->insert('notif', $tokenData);
                return true;
        } else {
            unset($tokenData['token']);
            $this->db->where('token', $token);
            $this->db->update('notif', $tokenData);
            return false;
        }
    }

    public function getToken($user = null) {
        if ($user != null) {
            $this->db->where('user', $user);
        }
        $query = $this->db->get('notif');
        $data = $query->result();

        return $data;
    }

    public function sendMessage($token, $body = null, $action = null , $title = null) {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();
        $icon = base_url() . "asset/images/icons/icon-48x48.png";
        if ($title == null) {
            $title = "Hi-Trip Di sini";
        }
        curl_setopt($ch, CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"notification\": {\n    \"title\": \"$title\",\n    \"body\": \"$body\",\n   \"click_action\": \"$action\"\n  },\n  \"to\": \"$token\"\n}");
        
        $headers = array();
        $headers[] = 'Authorization: key=AAAA9Ed6YFg:APA91bFWAZUaIUx8DWyNLmf9WmXXXashu1iYVl2owyYyuITge0AYPLKAZoozdURXNovFEsm9Briuw0aWAXJMhE2mC5UYXjBZY2_ta4rMViRUXl-2ouuinUnzvq2G6dovUNIuq-acaC4w';
        $headers[] = 'Content-Type: application/json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        
        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
    }

    public function sendBroadcastMessage($id_paket, $body = null, $action = null) {
        // $this->db->where('id_paket', $id_paket);
        // $data = $this->db->get('program_member')->result();

        // $jamaah = $this->getToken('j');

        
        $this->db->select('*');
        $this->db->from('program_member a');
        $this->db->join('paket_umroh b', 'b.id_paket = a.id_paket');
        $this->db->join('notif c', 'c.user_id = a.id_member');
        $this->db->where('c.user', 'j');
        $this->db->where('b.id_paket', $id_paket);
        $query = $this->db->get('')->result();
        
        if (!empty($query)) {
            foreach($query as $q) {
                $result = $this->sendMessage($q->token, $body, $action, "Ada info manasik nih buat kamu 😊😊");
            }
            return true ;
        } else {
            return false ;
        }
    }

    public function sendPembayaranMessage($id_member, $body = null, $action = null, $title = null) {
        $this->db->select('*');
        $this->db->from('program_member a');
        $this->db->join('notif b', 'b.user_id = a.id_member');
        $this->db->where('b.user', 'j');
        $this->db->where('a.id_member', $id_member);
        $query = $this->db->get('')->result();

        if (!empty($query)) {
            foreach($query as $q) {
                $result = $this->sendMessage($q->token, $body, null, $title);
            }
            return true;
        } else {
            return false ;
        }
    }

    public function sendPackageNotif($id_paket, $diskon) {
        $notif = $this->db->get('notif')->result();
        $this->load->library('money');
        $discountFormat = $this->money->hargaDiscountFormat($diskon);
        $this->load->model('paketUmroh');
        $paket = $this->paketUmroh->getPackage($id_paket, false, false) ;
        $this->load->library('date');
        $tgl = $this->date->convert_date_indo($paket->tanggal_berangkat);
        $paketFull = "$paket->nama_paket ($tgl)";
        if ($diskon == 0 || $diskon == '' || $diskon == null) {
            $text = "$paketFull \n 😍🕋 Cusss cek sekarang~";
        } else {
            $text = "$paketFull \nDapatkan DISCOUNT hingga $discountFormat \n 😍🕋 Cusss cek sekarang~";
        }
        if($notif) {
            foreach ($notif as $notify) {
                $this->sendMessage($notify->token, $text, base_url("jamaah/detail_paket?id=$id_paket"), "Ada Paket Umroh Baru nih!" );
            }
        } else {
            return false ;
        }

        return true ;
    }

    public function sendAgenPackageNotif($id, $diskon) {
        $this->db->where('user', 'k');
        $notif = $this->db->get('notif')->result();
        $this->load->model('agenPaket');
        // belom kelar
        $program = $this->agenPaket->getAgenPackage($id, false, false) ;
        $this->load->library('date');
        $tgl = $this->date->convert_date_indo($program->tanggal);
        $paketFull = "$program->nama_paket ($tgl)";
        // if ($diskon == 0 || $diskon == '' || $diskon == null) {
        //     $text = "$paketFull \n 😍🕋 Cusss cek sekarang~";
        // } else {
        //     $text = "$paketFull \nDapatkan DISCOUNT hingga $discountFormat \n 😍🕋 Cusss cek sekarang~";
        // }
        $text = "Ikuti $paketFull \n 😍 Cusss cek sekarang~";
        if($notif) {
            foreach ($notif as $notify) {
                $this->sendMessage($notify->token, $text, base_url("jamaah/detail_paket?id=$id"), "Kini telah hadir!" );
            }
        } else {
            return false ;
        }

        return true ;
    }

    public function sendEditPackageNotif() {
        $notif = $this->db->get('notif')->result();
        // $this->load->model('paketUmroh');
        // $paket = $this->paketUmroh->getPackage($id_paket, false, false) ;
        // $this->load->library('date');
        // $tgl = $this->date->convert_date_indo($paket->tanggal_berangkat);
        // $paketFull = "$paket->nama_paket ($tgl)";
        $text = "Kreasikan notification sesuai kebutuhanmu";
        if($notif) {
            foreach ($notif as $notify) {
                $this->sendMessage($notify->token, $text, base_url("jamaah/home"), "🔔 Fitur Push Notification 🔔" );
            }
        } else {
            return false ;
        }

        return true ;
    }

    public function sendNotifPelunasan() {
        $this->db->select('*');
        $this->db->from('program_member a');
        $this->db->join('notif b', 'b.user_id = a.id_member');
        $this->db->join('paket_umroh c', 'a.id_paket = c.id_paket');
        $this->db->where('b.user', 'j');
        $this->db->where('a.lunas', 2);
        $this->db->where('c.tanggal_berangkat >', date('Y-m-d'));
        $this->db->where('c.publish', 1);
        $this->db->where('DATEDIFF(c.tanggal_berangkat, NOW()) <= 50');
        $this->db->where('DATEDIFF(c.tanggal_berangkat, NOW()) >= 30');
        $query = $this->db->get()->result();
        // echo '<pre>';
        // print_r($query);
        // exit();

        if ($query) {
            foreach ($query as $q) {
                $this->load->library('calculate');
                $countdown = $this->calculate->dateDiff($q->tanggal_berangkat, date('Y-m-d'));
                // echo '<pre>';
                // print_r($countdown);
                // exit();
                if ($countdown <= 50 && $countdown > 45) {
                    $tanggal = new DateTime($q->tanggal_berangkat);
                    $tanggal->modify('-45 days');
                    $h_45 = $tanggal->format("j F Y");
                    $this->sendMessage($q->token, '📌 Mohon lakukan pelunasan umroh sebelum JATUH TEMPO tanggal' . $h_45, base_url('jamaah/pembayaran/metode'), "PERHATIAN 🔔");
                } else if ($countdown <= 45 && $countdown > 40) {
                    $this->sendMessage($q->token, '⏰ Segera lakukan pelunasan umroh karena telah JATUH TEMPO', base_url('jamaah/pembayaran/metode'), "PERHATIAN 🔔");
                } else if ($countdown <= 40 && $countdown >= 30) {
                    $this->sendMessage($q->token, '⏰ Segera lakukan pelunasan umroh sebelum seat TERCANCEL otomatis', base_url('jamaah/pembayaran/metode'), "PERHATIAN 🔔");
                }
            }
        }
        else {
            return false;
        }
    }

    public function sendNotifPelunasan2() {
        $this->db->select('*');
        $this->db->from('program_member a');
        $this->db->join('notif b', 'b.user_id = a.id_member');
        $this->db->join('paket_umroh c', 'a.id_paket = c.id_paket');
        $this->db->where('b.user', 'j');
        $this->db->where('a.lunas', 2);
        $this->db->where('c.tanggal_berangkat >', date('Y-m-d'));
        $this->db->where('c.publish', 1);
        $this->db->where('DATEDIFF(c.tanggal_berangkat, NOW()) <= 45');
        $this->db->where('DATEDIFF(c.tanggal_berangkat, NOW()) >= 30');
        $query = $this->db->get()->result();
        if ($query) {
            foreach ($query as $q) {
                $this->load->library('calculate');
                $countdown = $this->calculate->dateDiff($q->tanggal_berangkat, date('Y-m-d'));
                if ($countdown <= 45 && $countdown > 40) {
                    $this->sendMessage($q->token, '⏰ Segera lakukan pelunasan umroh karena telah JATUH TEMPO', base_url('jamaah/pembayaran/metode'), "PERHATIAN 🔔");
                } else if ($countdown <= 40 && $countdown >= 30) {
                    $this->sendMessage($q->token, '⏰ Segera lakukan pelunasan umroh sebelum seat TERCANCEL otomatis', base_url('jamaah/pembayaran/metode'), "PERHATIAN 🔔");
                }
            }
        }
        else {
            return false;
        }
    }

    public function sendNotifPelunasan3() {
        $this->db->select('*');
        $this->db->from('program_member a');
        $this->db->join('notif b', 'b.user_id = a.id_member');
        $this->db->join('paket_umroh c', 'a.id_paket = c.id_paket');
        $this->db->where('b.user', 'j');
        $this->db->where('a.lunas', 2);
        $this->db->where('c.tanggal_berangkat >', date('Y-m-d'));
        $this->db->where('c.publish', 1);
        $this->db->where('DATEDIFF(c.tanggal_berangkat, NOW()) <= 40');
        $this->db->where('DATEDIFF(c.tanggal_berangkat, NOW()) >= 30');
        $query = $this->db->get()->result();
        if ($query) {
            foreach ($query as $q) {
                $this->load->library('calculate');
                $countdown = $this->calculate->dateDiff($q->tanggal_berangkat, date('Y-m-d'));
                if ($countdown <= 40 && $countdown >= 30) {
                    $this->sendMessage($q->token, '⏰ Segera lakukan pelunasan umroh sebelum seat TERCANCEL otomatis', base_url('jamaah/pembayaran/metode'), "PERHATIAN 🔔");
                }
            }
        }
        else {
            return false;
        }
    }

    public function sendNotifAfterDP() {
        $this->db->select('*');
        $this->db->from('program_member a');
        $this->db->join('notif b', 'b.user_id = a.id_member');
        $this->db->join('paket_umroh c', 'a.id_paket = c.id_paket');
        $this->db->where('b.user', 'j');
        $this->db->where('c.tanggal_berangkat >', date('Y-m-d'));
        $this->db->where('c.publish', 1);
        $this->db->where('DATEDIFF(c.tanggal_berangkat, a.tgl_regist) <= 45');
        $this->db->where('DATEDIFF(c.tanggal_berangkat, a.tgl_regist) >= 21');
        $query = $this->db->get()->result();
        
        // set waktu pelunasan
        if ($query) {
            foreach ($query as $key => $q) {
                $this->load->library('calculate');
                $pelunasan = $this->calculate->dateDiff($q->tanggal_berangkat, date('Y-m-d', strtotime($q->tgl_regist)));
                if ($pelunasan <= 45 && $pelunasan >= 41) {
                    $waktuPelunasan = date('Y-m-d', strtotime($q->tgl_regist . '+7days'));
                    $query[$key]->waktu_pelunasan = $waktuPelunasan ;
                    $query[$key]->nilai_dp = $q->dp45 ;
                } else if ($pelunasan <= 40 && $pelunasan >= 36) {
                    $waktuPelunasan = date('Y-m-d', strtotime($q->tgl_regist . '+5days'));
                    $query[$key]->waktu_pelunasan = $waktuPelunasan ;
                    $query[$key]->nilai_dp = $q->dp40 ;
                } else if ($pelunasan <= 35 && $pelunasan >= 26) {
                    $waktuPelunasan = date('Y-m-d', strtotime($q->tgl_regist . '+5days'));
                    $query[$key]->waktu_pelunasan = $waktuPelunasan ;
                    $query[$key]->nilai_dp = $q->dp35 ;
                } else if ($pelunasan <= 25 && $pelunasan >= 21) {
                    $waktuPelunasan = date('Y-m-d', strtotime($q->tgl_regist . '+3days'));
                    $query[$key]->waktu_pelunasan = $waktuPelunasan ;
                    $query[$key]->nilai_dp = $q->dp25 ;
                }
            }
        }

        // send notification
        if ($query) {
            foreach ($query as $qry) {
                if ($qry->waktu_pelunasan <= date('Y-m-d')) {
                    // send notification
                }
            }
        }
    }
}